services:
  build-web:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    volumes:
      - web-build:/var/www/www



  nginx:
    depends_on:
      - build-web
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    volumes:
      - web-build:/usr/share/nginx/html
      - /data/certbot/letsencrypt:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    ports:
      - ${SERVICE_PORT}:80

volumes:
  web-build:
