name: "Deploy to server"

on:
    push:
        branches: ["main"]

jobs:
   re-build-docker-image:
        runs-on: ubuntu-latest
        steps:
            -
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.DEV_HOST }}
                    username: ${{ secrets.DEV_USER }}
                    key: ${{ secrets.DEV_SSH }}

                    script: |
                        cd /var/projects/dociFY
                        docker compose down
                        docker system prune
                        sudo git pull
                        docker compose up --build -d
